### ISSUE TITLE
Issues with Dataset

### ISSUE THREAD

**Issue by cuitaoyong** [keiradams/SQUID#3]
Hello!After downloading the training data from https://figshare.com/s/3d2f8fd57d9a65fe237e, I want to re-train the graph generator and the scorer, but I met the issues “No such file or directory: 'data/MOSES2/training_split_arrays/original_index.npy'”“No such file or directory: 'data/MOSES2/max_future_rocs_data_artificial_alpha_2_0/computed_max_future_rocs.npy'” , would you help me?

**Comment by keiradams** [comment]
Hi! I just (re)downloaded `data.zip` from Figshare and confirmed that the two files you mentioned are included. I'd suggest that you try re-downloading `data.zip`, unzip the data, and manually check that your missing files are correctly downloaded. Also, make sure that you place the unzipped `data/` in the same directory as the training scripts.

Let me know if your issues persist!
